version: "3" # docker-compose version
services:
  backend:
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    container_name: aretha-backend
    build:
      context: ./backend
    environment:
      ARETHA_DEBUG: "True"
      ARETHA_DB_HOST: localhost
  database:
    container_name: aretha-database
    image: postgres
    environment:
      - POSTGRES_USER=aretha
      - POSTGRES_PASSWORD=aretha
      - POSTGRES_DB=aretha
    ports:
      - "5432:5432"
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/init.sql
