version: "3" # docker-compose version
services:
  aretha_test_db:
    image: postgres
    environment:
      - POSTGRES_USER=aretha
      - POSTGRES_PASSWORD=aretha
      - POSTGRES_DB=aretha
    ports:
      - "5433:5432"
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/init.sql
      
  aretha_db:
    image: postgres
    environment:
      - POSTGRES_USER=aretha
      - POSTGRES_PASSWORD=aretha
      - POSTGRES_DB=aretha
    ports:
      - "5432:5432"
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/init.sql
