version: "3" # docker-compose version
services:
  backend:
    container_name: aretha-backend
    build:
      context: ./backend
    ports:
      - "4201:4201"
    environment:
      ARETHA_DB_HOST: aretha-database
  database:
    container_name: aretha-databse
    image: postgres
    environment:
      - POSTGRES_USER=aretha
      - POSTGRES_PASSWORD=aretha
      - POSTGRES_DB=aretha
    ports:
      - "5432:5432"
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/init.sql
